---
- name: Gather distribution vars
  include_vars: '{{ ansible_os_family | lower }}.yml'

- name: Install prerequisites
  package:
          name: "{{ dependencies }}"
          state: present

- name: Check opensips-cp dir content
  stat:
          path: '{{ opensips_cp_dir }}'
  register: res

- name: Deploy OpenSIPS CP source
  git:
          repo: "{{ opensips_cp_git_url }}"
          dest: "{{ opensips_cp_dir }}"
          version: "{{ opensips_cp_git_branch }}"
  when: res.stat.isdir is not defined

- name: Configure Apache
  template:
          src: 000-default.conf.j2
          dest: "{{ apache_dir }}httpd-opensips.conf"
  notify:
        - restart apache

- name: Enable site
  shell:
          cmd: a2ensite httpd-opensips
  when: ansible_os_family == "Debian"
  notify:
        - restart apache 

          #- name: Configure Cron
          #  cron:
          #cron_file: "{{ opensips_cp_dir }}/config/tools/system/smonitor/opensips_stats_cron"
          #user: root
          #

- name: Configure cron
  copy:
          src: "{{opensips_cp_dir}}/config/tools/system/smonitor/opensips_stats_cron"
          dest: /etc/cron.d

- name: Configure database
  template:
          src: db.inc.php.j2
          dest: "{{ opensips_cp_dir }}/config/db.inc.php"

- name: Configure modules
  template:
          src: modules.inc.php.j2
          dest: "{{ opensips_cp_dir }}/config/modules.inc.php"

- name: Configure global options
  template:
          src: globals.php.j2
          dest: "{{ opensips_cp_dir }}/config/globals.php"

- name: Boxes definition
  template:
          src: boxes.global.inc.php.j2  
          dest: "{{ opensips_cp_dir }}/config/boxes.global.inc.php"

- name: Create OCP tables
  shell: 
        cmd: "mysql -Dopensips  < {{ opensips_cp_dir }}/config/db_schema.mysql"
